name: cardano_jsonrpc
description: Dart library to interact with Cardano JSON RPC and create and manage wallets
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_rpc_client: ^1.0.2
  ninja_ed25519: ^1.0.1
  sha3: ^0.2.0
  bs58check: ^1.0.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.11

dependency_overrides:
  ninja_ed25519:
    path: ../../dart/ninja_ed25519
